name: Build Debian packaging

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_debs:
    name: Build debs on linux x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: automatika-robotics/create-ros-debs-action@v1
        with:
          ros-versions-matrix: 'humble iron jazzy rolling'

      - uses: actions/upload-artifact@v4
        with:
          name: debs-${{ strategy.job-index }}
          path: ./debs/*.deb
